server:
  port: 3001
  
spring:
  application:
    name: timerfy-server
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # CORS Configuration
  web:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:5173"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      
# WebSocket Configuration
websocket:
  allowed-origins: "http://localhost:3000,http://localhost:5173"
  
# Application Configuration
timerfy:
  room:
    expiration: 86400 # 24 hours in seconds
    max-timers: 10
    max-users: 50
  cleanup:
    interval: 3600 # 1 hour in seconds
    
# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html